import type { Locale } from "@/lib/i18n/messages";

/**
 * Curated, family-friendly "dare" suggestions used by the dice button in the
 * challenge composer. Pure data + a random picker — no I/O, so it stays in
 * `lib/domain` and is safe to import on the client.
 *
 * Constraints (mirror the punishment validation in `challenges-service`):
 * every entry MUST be between 3 and 220 characters and must stay clean enough
 * to pass content moderation (no gambling/NSFW/gore/illegal references).
 */

const VI_SUGGESTIONS: readonly string[] = [
  "Hát một đoạn quốc ca bằng giọng mèo kêu.",
  "Gọi điện cho người thứ 5 trong danh bạ và hát chúc mừng sinh nhật, kể cả khi hôm nay không phải sinh nhật họ.",
  "Đăng story khoe rằng mình vừa thắng giải 'Người đẹp dịu dàng' của xóm.",
  "Nhảy điệu con vịt giữa phòng trong 30 giây, không được cười.",
  "Đọc tin nhắn gần nhất với mẹ bằng giọng phát thanh viên thời sự.",
  "Bắt chước tiếng gà gáy mỗi khi có người nói chuyện trong 10 phút tới.",
  "Tự quay video tập thể dục buổi sáng và caption 'thân hình mơ ước'.",
  "Nói chuyện bằng vần điệu thơ lục bát trong suốt 5 phút.",
  "Đổi ảnh đại diện thành ảnh chính mình lúc xấu nhất trong 1 tiếng.",
  "Gọi tên người yêu cũ ra và hét 'anh/em đã sai rồi' ba lần.",
  "Ăn một thìa tương ớt rồi mỉm cười nói 'ngon tuyệt'.",
  "Diễn lại cảnh phim ngôn tình sến súa nhất bạn từng xem.",
  "Đi lại quanh phòng như người mẫu sàn diễn trong 1 phút.",
  "Nhắn tin cho sếp/thầy cô: 'Hôm nay trông anh/chị rạng rỡ ghê'.",
  "Hát rap về món ăn yêu thích của bạn trong 20 giây.",
  "Làm mặt xấu nhất có thể và giữ nguyên trong khi mọi người chụp ảnh.",
  "Bắt chước cách đi của một con cua trong 30 giây.",
  "Giả làm MC giới thiệu bữa ăn tối như chương trình ẩm thực 5 sao.",
  "Đọc to ba bình luận dạo gần đây nhất trên mạng xã hội của bạn.",
  "Nói 'Tôi yêu các bạn' với giọng robot mỗi 2 phút trong 10 phút tới.",
  "Tự vẽ chân dung mình trong 30 giây rồi khoe cho cả phòng.",
  "Hát một bài thiếu nhi với vẻ mặt nghiêm túc như đang hát opera.",
  "Đứng lên giả vờ làm phát thanh viên dự báo thời tiết phòng khách.",
  "Gọi video cho một người bạn và chỉ nói chuyện bằng tiếng 'meo meo'.",
  "Diễn tả cảm xúc khi hết tiền cuối tháng chỉ bằng nét mặt.",
  "Nhảy như đang giẫm phải than nóng trong 20 giây.",
  "Đọc thực đơn quán ăn yêu thích như đang đọc thơ tình.",
  "Bắt chước giọng nói của một nhân vật hoạt hình bạn thích nhất.",
  "Tự khen mình 10 câu liên tục mà không lặp lại từ nào.",
  "Giả vờ đang phỏng vấn xin việc làm phi hành gia trong 1 phút.",
  "Hát 'Happy Birthday' nhưng thay tên thành tên của bản thân.",
  "Diễn lại pha ngã 'huyền thoại' gần nhất của bạn cho cả phòng xem.",
  "Nói chuyện chỉ bằng câu hỏi trong 3 phút tiếp theo.",
  "Bắt chước tiếng còi xe cứu thương mỗi khi ai đó đứng dậy.",
  "Đăng một status triết lý sâu sắc về… cọng rau muống.",
  "Làm động tác chống đẩy 5 cái rồi tuyên bố 'thế là đủ cho hôm nay'.",
  "Giả làm hướng dẫn viên du lịch giới thiệu căn phòng bạn đang ngồi.",
  "Hát một câu vọng cổ ngẫu hứng về việc thua kèo.",
  "Tự đặt cho mình một biệt danh siêu anh hùng và giới thiệu thật hùng hồn.",
  "Đi bằng đầu gối quanh phòng một vòng.",
  "Bắt chước tiếng động cơ xe máy nổ máy khó khăn vào buổi sáng.",
  "Nói lời tỏ tình thật sến với chiếc điện thoại của bạn.",
  "Diễn cảnh khóc trong phim Hàn nhưng không được dùng nước mắt thật.",
  "Đọc bảng cửu chương 9 bằng giọng hát.",
  "Giả vờ làm bình luận viên bóng đá tường thuật cảnh bạn uống nước.",
  "Nhảy flashmob một mình trong 30 giây với bài nhạc bất kỳ.",
  "Tự sướng kể về thành tích 'ngủ nướng vô địch' của bản thân.",
  "Bắt chước cách cười của một nhân vật phản diện trong phim.",
  "Gọi cho người bạn thân và đọc một bài thơ tự sáng tác về họ.",
  "Đứng nghiêm chào cờ tưởng tượng và hát quốc ca thật to.",
  "Làm dáng và chụp 5 kiểu ảnh 'sống ảo' khác nhau trong 1 phút.",
  "Diễn tả một ngày của con sên bằng ngôn ngữ cơ thể.",
  "Nói tất cả mọi thứ bằng giọng thì thầm bí mật trong 5 phút.",
  "Bắt chước điệu bộ của giáo viên/sếp bạn ghét nhất (nhẹ nhàng thôi).",
  "Hát một đoạn nhạc quảng cáo mì gói mà bạn còn nhớ.",
  "Giả làm người mẫu quảng cáo kem đánh răng, cười thật tươi.",
  "Tự quay video review chiếc dép của mình như review điện thoại đời mới.",
  "Đọc to dòng tin nhắn cuối cùng trong nhóm chat gia đình.",
  "Nhảy điệu 'gà công nghiệp' do bạn tự nghĩ ra trong 20 giây.",
  "Diễn lại cảnh bạn nhìn thấy hóa đơn tiền điện tháng này.",
  "Bắt chước tiếng các con vật trong sở thú liên tục trong 1 phút.",
  "Tự giới thiệu bản thân như một sản phẩm đang được rao bán.",
  "Hát một bài hát buồn nhưng vừa hát vừa nhảy tưng bừng.",
  "Giả vờ đang ăn một bữa tiệc sang trọng với… không khí.",
  "Đọc lời bài hát yêu thích như đang đọc điếu văn.",
  "Bắt chước dáng đi của một người vừa tập gym xong.",
  "Tự tổ chức một buổi họp báo xin lỗi vì… ngủ quên báo thức.",
  "Diễn cảnh siêu nhân biến hình giữa phòng khách.",
  "Nói chuyện bằng giọng người ngoài hành tinh trong 3 phút.",
  "Hát một bài tủ nhưng phải đứng bằng một chân suốt cả bài.",
  "Giả làm cô giáo dạy múa và bắt cả phòng tập theo 3 động tác.",
  "Tự quay clip ASMR ăn… một miếng bánh mì khô.",
  "Đọc to một câu chuyện cười nhưng phải cố không được cười.",
  "Bắt chước cách phụ huynh gọi bạn về ăn cơm hồi nhỏ.",
  "Diễn tả cảm giác đi học muộn bằng một điệu nhảy.",
  "Hát đếm số từ 1 đến 20 theo giai điệu một bài hát nổi tiếng.",
  "Giả làm trọng tài thổi còi và rút thẻ đỏ một người trong phòng.",
  "Tự khen món ăn dở nhất bạn từng nấu như một đầu bếp 3 sao.",
  "Đi catwalk với một quyển sách đội trên đầu, không được rơi.",
  "Bắt chước giọng đọc quảng cáo thuốc trên đài phát thanh.",
  "Nói câu 'Tôi là người tuyệt vời nhất' bằng 5 ngữ điệu khác nhau.",
  "Diễn lại khoảnh khắc bạn trượt chân nhưng giả vờ như đang nhảy.",
  "Hát một bài hát chỉ bằng âm 'la la la' từ đầu đến cuối.",
  "Giả làm thầy bói xem chỉ tay cho một người và phán toàn điều hài hước.",
  "Tự đặt một câu đố mà chính bạn cũng không biết đáp án.",
  "Bắt chước tiếng máy giặt đang vắt quần áo trong 20 giây.",
  "Đọc thật cảm xúc danh sách đồ cần mua đi chợ.",
  "Diễn cảnh hai người cãi nhau nhưng đóng cả hai vai.",
  "Hát karaoke trong tưởng tượng và 'cháy' hết mình trong 30 giây.",
  "Giả vờ là người dẫn chương trình thời trang, bình luận trang phục mọi người.",
  "Tự nhận giải Oscar tưởng tượng với một bài phát biểu đầy nước mắt.",
  "Bắt chước cách một em bé tập đi quanh phòng.",
  "Đọc to một đoạn quảng cáo bất động sản nhưng là quảng cáo cái ghế bạn ngồi.",
  "Diễn tả cảm xúc khi wifi bị rớt mạng chỉ bằng nét mặt và tay.",
  "Hát một bài và sau mỗi câu phải thêm tiếng 'ụ oa' của trẻ con.",
  "Giả làm phóng viên hiện trường tường thuật cảnh… cốc nước đổ.",
  "Tự nghĩ ra một điệu nhảy ăn mừng và biểu diễn ngay.",
  "Bắt chước cách nói chuyện của một cụ già 90 tuổi.",
  "Đọc to câu thần chú 'tôi sẽ không thua kèo lần sau' 10 lần.",
  "Diễn cảnh bạn cố mở một lọ dưa muối nhưng không được.",
  "Hát một bài nhưng cứ 5 giây lại đổi sang một thể loại nhạc khác.",
  "Giả làm hướng dẫn viên thể dục buổi sáng trên tivi.",
  "Tự quay một video 'unbox' chiếc bút bi như mở hộp hàng hiệu.",
  "Bắt chước biểu cảm của bạn khi nhìn thấy bài kiểm tra điểm kém.",
  "Đọc to lời chúc mừng năm mới nhưng dành cho… chú chó nhà hàng xóm.",
  "Diễn tả một cơn bão bằng cách dùng cả cơ thể.",
  "Hát một câu rồi để người bên cạnh hát tiếp, cứ thế đến hết bài.",
  "Giả làm thám tử điều tra vụ 'ai ăn vụng đồ trong tủ lạnh'.",
  "Tự thuyết trình 1 phút về lợi ích của việc… ngủ trưa.",
  "Bắt chước tiếng còi tàu hỏa mỗi khi có người cười.",
  "Đọc to một câu tiếng Anh bồi và tự dịch sai be bét.",
  "Diễn cảnh bạn vừa trúng số nhưng tờ vé bị gió thổi bay.",
  "Hát một bài hát ru nhưng với năng lượng của một bài nhạc sàn.",
  "Giả làm chuyên gia trang điểm và 'tư vấn' cho một người trong phòng.",
  "Tự đứng lên và đọc một bài diễn văn nhậm chức 'tổ trưởng vui vẻ'.",
  "Bắt chước cách mèo nằm phơi nắng trong 30 giây.",
  "Đọc to nội quy phòng do chính bạn bịa ra ngay lúc đó.",
  "Diễn tả cảnh đi trên dây làm xiếc giữa phòng.",
  "Hát một bài nhạc đỏ với điệu bộ của ca sĩ thần tượng.",
  "Giả làm bác sĩ khám bệnh và chẩn đoán mọi người mắc bệnh 'lười'.",
  "Tự viết và đọc một bài thơ 4 câu về chiếc bình nước.",
  "Bắt chước cách một người đang cố nhịn hắt hơi.",
  "Đọc to dòng trạng thái mạng xã hội đầu tiên bạn từng đăng.",
  "Diễn cảnh bạn là một chiếc lá đang rụng vào mùa thu.",
  "Hát một bài và mỗi từ phải kéo dài thật lê thê như opera.",
  "Giả làm người bán hàng rong rao bán món đồ gần bạn nhất.",
  "Tự đặt tên khoa học hài hước cho ba người trong phòng.",
  "Bắt chước cách đi của một con khủng long T-Rex tay ngắn.",
  "Đọc to một câu tục ngữ nhưng giải thích sai hoàn toàn.",
  "Diễn tả cảm xúc khi nhận lương bằng một điệu nhảy ăn mừng.",
  "Hát một bài hát tiếng nước ngoài mà bạn chỉ hát 'bừa' theo giai điệu.",
  "Giả làm robot hết pin từ từ ngừng hoạt động giữa câu nói.",
  "Tự nhận mình là 'đại sứ thương hiệu' của một món ăn vặt và quảng cáo nó.",
  "Bắt chước cách một người ngái ngủ tìm điện thoại lúc nửa đêm.",
  "Đọc to lời tự sự của một chiếc tất bị thất lạc đôi.",
  "Diễn cảnh bạn cố tỏ ra bình tĩnh khi thấy con gián bay.",
  "Hát một bài nhưng phải bịt mũi từ đầu đến cuối.",
  "Giả làm huấn luyện viên hô hào cả phòng làm 3 động tác khởi động.",
  "Tự bình chọn mình là 'nhân vật của năm' và đọc lý do thật long trọng.",
  "Bắt chước cách một con chó vẫy đuôi khi chủ về.",
  "Đọc to một đoạn hướng dẫn sử dụng nhưng cho… một cục tẩy.",
  "Diễn tả cảnh trời mưa to bằng âm thanh do bạn tự tạo.",
  "Hát một bài và thay toàn bộ lời bằng tên các món ăn.",
  "Giả làm nhà phê bình nghệ thuật bình luận về bức tường trước mặt.",
  "Tự kể một câu chuyện ma nhưng cái kết phải thật buồn cười.",
  "Bắt chước cách một người cố tỏ ra ngầu khi vừa vấp ngã.",
  "Đọc to ba từ khó phát âm liên tiếp mà không được vấp.",
  "Diễn cảnh bạn là chiếc bánh mì đang được nướng trong lò.",
  "Hát một bài hát thiếu nhi nhưng với phong cách ca sĩ nhạc rock.",
  "Giả làm phi công thông báo cho hành khách trên 'chuyến bay phòng khách'.",
  "Tự nghĩ ra một câu khẩu hiệu cổ động cho đội bạn yêu thích và hô to.",
  "Bắt chước cách một người đang xem phim kinh dị một mình.",
  "Đọc to một danh sách việc cần làm nhưng toàn việc 'không bao giờ làm'.",
  "Diễn tả cảm giác chờ ấm nước sôi bằng nét mặt sốt ruột.",
  "Hát một bài và để mọi người vỗ tay sai nhịp trêu bạn.",
  "Giả làm người dẫn chương trình game show, đặt một câu hỏi dễ ợt.",
  "Tự khen ngợi đôi dép của mình bằng một bài diễn thuyết 30 giây.",
  "Bắt chước cách một con ếch nhảy quanh phòng 3 lần.",
  "Đọc to câu 'tôi rất nghiêm túc' với vẻ mặt buồn cười nhất có thể.",
  "Diễn cảnh bạn là một bông hoa đang nở dưới ánh nắng.",
  "Hát một bài và cứ mỗi câu lại đổi sang một giọng vùng miền khác.",
  "Giả làm chuyên gia phong thủy phán về cách kê bàn ghế trong phòng.",
  "Tự viết một dòng caption 'thả thính' rồi đọc to cho cả phòng nghe.",
  "Bắt chước cách một người mới ngủ dậy chưa tỉnh nói chuyện.",
  "Đọc to một đoạn rap freestyle về việc rửa bát.",
  "Diễn tả cảnh bạn cố nhịn cười trong một cuộc họp quan trọng.",
  "Hát một bài hát yêu thích nhưng thay mọi nguyên âm thành 'ô'.",
  "Giả làm hướng dẫn viên bảo tàng giới thiệu chiếc remote tivi như cổ vật.",
  "Tự đặt một lời tiên tri vui về tương lai của người ngồi cạnh.",
  "Bắt chước cách một người chụp ảnh đồ ăn trước khi ăn.",
  "Đọc to lời cảm ơn dài lê thê như nhận giải thưởng lớn vì… ăn hết bát cơm.",
  "Diễn cảnh bạn là một cây xương rồng kiêu hãnh giữa sa mạc.",
  "Hát một bài và phải nhún nhảy theo như đang trên sân khấu lớn.",
  "Giả làm thuyết minh viên phim tài liệu về loài người ngồi trong phòng.",
  "Tự nghĩ ra một điệu chào bí mật và dạy cho một người trong phòng.",
  "Bắt chước cách một người đang cố mở nắp chai nước ngọt bị kẹt.",
  "Đọc to một câu chúc đám cưới nhưng dành cho hai chiếc đũa.",
  "Diễn tả một ngày mưa buồn bằng một điệu nhảy chậm.",
  "Hát một bài và mỗi lần hết hơi phải hét lên 'tôi vẫn ổn'.",
  "Giả làm chuyên gia ẩm thực nếm thử một ly nước lọc và bình luận sâu sắc.",
  "Tự giới thiệu bản thân bằng một bài thơ con cóc 4 câu.",
  "Bắt chước cách một người chờ thang máy mãi không tới.",
  "Đọc to nội dung quảng cáo do bạn bịa ra cho chiếc gối ôm.",
  "Diễn cảnh bạn là một chú robot lau nhà bị mắc kẹt ở góc tường.",
  "Hát một bài và phải làm động tác tay như đang chỉ huy dàn nhạc.",
  "Giả làm vận động viên nhận huy chương vàng và hát quốc ca đầy tự hào.",
  "Tự bình luận về kiểu tóc của chính mình như một nhà tạo mẫu nổi tiếng.",
  "Bắt chước cách một người cố tỏ ra hiểu bài khi bị gọi lên bảng.",
  "Đọc to một đoạn 'tâm sự thầm kín' của chiếc tủ lạnh nhà bạn.",
  "Diễn tả cảm giác ăn phải món quá cay chỉ bằng nét mặt và tay.",
  "Hát một bài và phải nhảy lò cò suốt cả bài.",
  "Giả làm người mẫu ảnh tạp chí, đổi 5 dáng pose trong 15 giây.",
  "Tự phong cho mình một chức danh hoàng gia và ra lệnh hài hước cho cả phòng.",
  "Bắt chước cách một con chim bồ câu gật gù đi tìm thức ăn.",
  "Đọc to một bản tin thời sự về việc bạn vừa thua kèo, giọng thật nghiêm túc.",
  "Diễn cảnh bạn là một viên kẹo đang tan dần trong miệng ai đó.",
  "Hát một bài hát quen thuộc nhưng phải hát ngược thứ tự các câu.",
  "Giả làm hướng dẫn viên yoga và bắt cả phòng hít thở thật sâu 3 lần.",
  "Bắt chước cách một người cố tỏ ra tỉnh táo sau khi vừa ngủ gật.",
  "Tự đọc to lời quảng cáo về chính bản thân như đang bán một gói combo siêu hời.",
];

const EN_SUGGESTIONS: readonly string[] = [
  "Sing your national anthem entirely in cat meows.",
  "Call the 5th person in your contacts and sing happy birthday, even if it isn't their birthday.",
  "Post a story claiming you just won the neighborhood's 'Most Graceful Human' award.",
  "Do the duck dance in the middle of the room for 30 seconds without laughing.",
  "Read your most recent text to your mom like a serious news anchor.",
  "Crow like a rooster every time someone speaks for the next 10 minutes.",
  "Film your morning workout and caption it 'dream physique'.",
  "Speak only in rhyming couplets for the next 5 minutes.",
  "Set your profile picture to your worst-looking photo for one hour.",
  "Shout your ex's name and yell 'I was wrong!' three times.",
  "Eat a spoonful of chili sauce, then smile and say 'delicious'.",
  "Re-enact the cheesiest romance scene you've ever watched.",
  "Strut around the room like a runway model for one minute.",
  "Text your boss or teacher: 'You look absolutely radiant today.'",
  "Rap about your favorite food for 20 seconds.",
  "Make the ugliest face you can and hold it while everyone takes photos.",
  "Walk sideways like a crab for 30 seconds.",
  "Be the host of a 5-star cooking show introducing tonight's dinner.",
  "Read your three most recent social media comments out loud.",
  "Say 'I love you all' in a robot voice every 2 minutes for the next 10 minutes.",
  "Draw a self-portrait in 30 seconds and show it to everyone.",
  "Sing a children's song with the serious face of an opera singer.",
  "Stand up and deliver a living-room weather forecast.",
  "Video-call a friend and only communicate in 'meow meow' sounds.",
  "Express the feeling of being broke at month's end using only your face.",
  "Dance like you're stepping on hot coals for 20 seconds.",
  "Read your favorite restaurant's menu like it's a love poem.",
  "Imitate the voice of your favorite cartoon character.",
  "Compliment yourself 10 times in a row without repeating a single word.",
  "Pretend you're in a job interview to become an astronaut for one minute.",
  "Sing 'Happy Birthday' but replace the name with your own.",
  "Re-enact your most legendary recent stumble for the whole room.",
  "Speak only in questions for the next 3 minutes.",
  "Make an ambulance siren sound every time someone stands up.",
  "Post a deeply philosophical status about… a single blade of grass.",
  "Do 5 push-ups, then declare 'that's enough for today'.",
  "Be a tour guide introducing the room you're currently sitting in.",
  "Improvise a sad folk song about losing the bet.",
  "Give yourself a superhero nickname and introduce it dramatically.",
  "Walk one full lap around the room on your knees.",
  "Imitate a motorbike struggling to start on a cold morning.",
  "Make a heartfelt love confession to your phone.",
  "Act out a crying scene from a soap opera without any real tears.",
  "Recite the 9 times table in a singing voice.",
  "Be a sports commentator narrating yourself drinking a glass of water.",
  "Perform a one-person flashmob for 30 seconds to any song.",
  "Brag at length about your championship-level talent for sleeping in.",
  "Imitate the laugh of a movie villain.",
  "Call a close friend and read them a poem you wrote about them.",
  "Stand at attention for an imaginary flag and sing the anthem loudly.",
  "Strike 5 different 'influencer' photo poses in one minute.",
  "Act out a day in the life of a snail using only body language.",
  "Say everything in a secret whisper for the next 5 minutes.",
  "Gently imitate the mannerisms of a teacher or boss you find annoying.",
  "Sing an instant-noodle jingle that you still remember.",
  "Be a toothpaste commercial model with the brightest smile possible.",
  "Film a review of your slipper as if it were the latest smartphone.",
  "Read the last message in your family group chat out loud.",
  "Perform a 'factory chicken' dance you make up on the spot for 20 seconds.",
  "Re-enact your reaction to seeing this month's electricity bill.",
  "Make zoo animal noises non-stop for one minute.",
  "Introduce yourself as if you were a product being sold on TV.",
  "Sing a sad song while dancing joyfully the whole time.",
  "Pretend to enjoy a fancy banquet made entirely of… air.",
  "Read the lyrics of your favorite song like a funeral eulogy.",
  "Imitate the walk of someone who just finished a hard gym session.",
  "Hold a press conference apologizing for… sleeping through your alarm.",
  "Act out a superhero transformation in the middle of the living room.",
  "Speak in an alien voice for the next 3 minutes.",
  "Sing your signature song while standing on one leg the entire time.",
  "Be a dance teacher and make the room copy 3 of your moves.",
  "Film an ASMR clip of you eating… one dry piece of bread.",
  "Read a joke out loud while trying your hardest not to laugh.",
  "Imitate how your parents called you home for dinner as a kid.",
  "Express the feeling of being late for school through a dance.",
  "Count from 1 to 20 to the tune of a famous song.",
  "Be a referee, blow a whistle, and give someone in the room a red card.",
  "Praise the worst dish you've ever cooked like a 3-star chef.",
  "Catwalk with a book balanced on your head without dropping it.",
  "Imitate a radio voice reading a medicine advertisement.",
  "Say 'I am the most amazing person' in 5 different tones.",
  "Re-enact a moment you slipped, but pretend it was a dance move.",
  "Sing an entire song using only 'la la la'.",
  "Be a palm reader and predict only ridiculous things for one person.",
  "Pose a riddle that even you don't know the answer to.",
  "Imitate the sound of a washing machine on its spin cycle for 20 seconds.",
  "Read your grocery shopping list out loud with deep emotion.",
  "Act out an argument between two people by playing both roles.",
  "Sing imaginary karaoke and go all-out for 30 seconds.",
  "Be a fashion show host commenting on everyone's outfit.",
  "Accept an imaginary Oscar with a tearful acceptance speech.",
  "Imitate a baby learning to walk around the room.",
  "Read a real-estate ad out loud, but for the chair you're sitting on.",
  "Express a wifi outage using only your face and hands.",
  "Sing a song and add a baby's 'goo-goo ga-ga' after every line.",
  "Be a field reporter giving live coverage of… a spilled glass of water.",
  "Invent a victory dance and perform it right now.",
  "Imitate how a 90-year-old grandparent talks.",
  "Chant the spell 'I will not lose the bet next time' 10 times.",
  "Act out struggling to open a stubborn jar of pickles.",
  "Sing a song but switch to a different music genre every 5 seconds.",
  "Be a TV morning-exercise instructor.",
  "Film an 'unboxing' of a ballpoint pen like it's a luxury item.",
  "Imitate your face when you see a failed test paper.",
  "Read a happy new year greeting out loud, but to your neighbor's dog.",
  "Use your whole body to depict a thunderstorm.",
  "Sing one line, then let the person next to you sing the next, to the end.",
  "Be a detective investigating 'who snacked on the fridge food'.",
  "Give a one-minute presentation on the benefits of… afternoon naps.",
  "Make a train horn sound every time someone laughs.",
  "Read a sentence in broken English and mistranslate it terribly.",
  "Act out winning the lottery, then the ticket flies away in the wind.",
  "Sing a lullaby with the energy of a club dance track.",
  "Be a makeup artist 'consulting' one person in the room.",
  "Stand up and deliver an inauguration speech as 'Chief of Fun'.",
  "Imitate a cat sunbathing for 30 seconds.",
  "Read out house rules that you make up on the spot.",
  "Act out walking a circus tightrope across the room.",
  "Sing a patriotic song with the moves of your idol singer.",
  "Be a doctor diagnosing everyone with a case of 'laziness'.",
  "Write and read a 4-line poem about a water bottle.",
  "Imitate someone trying hard to hold back a sneeze.",
  "Read out loud the very first social media status you ever posted.",
  "Act out being a leaf falling in autumn.",
  "Sing a song and stretch every word out endlessly like opera.",
  "Be a street vendor loudly selling the nearest object to you.",
  "Give funny scientific names to three people in the room.",
  "Imitate the walk of a T-Rex with tiny little arms.",
  "Read a proverb out loud and explain it completely wrong.",
  "Express the joy of payday through a celebratory dance.",
  "Sing a foreign-language song by just faking the melody.",
  "Be a robot running out of battery, slowly freezing mid-sentence.",
  "Declare yourself the brand ambassador of a snack and advertise it.",
  "Imitate a sleepy person searching for their phone at midnight.",
  "Read aloud the inner monologue of a sock that lost its pair.",
  "Act out staying calm while a cockroach flies toward you.",
  "Sing a whole song while pinching your nose shut.",
  "Be a coach rallying the room through 3 warm-up moves.",
  "Vote yourself 'Person of the Year' and read your reasons solemnly.",
  "Imitate a dog wagging its tail when its owner comes home.",
  "Read out a user manual, but for… an eraser.",
  "Depict heavy rain using sound effects you make yourself.",
  "Sing a song but replace all the lyrics with names of foods.",
  "Be an art critic reviewing the wall in front of you.",
  "Tell a ghost story but with an ending that's hilariously sad.",
  "Imitate someone trying to look cool right after tripping.",
  "Read three tongue-twisters in a row without stumbling.",
  "Act out being a loaf of bread baking in the oven.",
  "Sing a children's song in the style of a rock singer.",
  "Be a pilot making an announcement on the 'living room flight'.",
  "Make up a cheering slogan for your favorite team and shout it.",
  "Imitate someone watching a horror movie all alone.",
  "Read out a to-do list full of things you'll 'never actually do'.",
  "Express the impatience of waiting for a kettle to boil using your face.",
  "Sing a song while everyone claps off-beat to throw you off.",
  "Be a game-show host asking one absurdly easy question.",
  "Praise your own slippers with a 30-second speech.",
  "Hop around the room like a frog three times.",
  "Say 'I am very serious' with the silliest face you can make.",
  "Act out being a flower blooming in the sunlight.",
  "Sing a song and switch to a different regional accent each line.",
  "Be a feng shui expert judging how the furniture is arranged.",
  "Write a flirty caption and read it out loud to the room.",
  "Imitate how someone talks when they just woke up and aren't awake yet.",
  "Perform a freestyle rap about doing the dishes.",
  "Act out holding back laughter during an important meeting.",
  "Sing your favorite song but replace every vowel with 'oh'.",
  "Be a museum guide introducing the TV remote as an ancient relic.",
  "Make a fun prophecy about the future of the person next to you.",
  "Imitate someone photographing their food before eating.",
  "Give a long-winded thank-you speech for… finishing your bowl of rice.",
  "Act out being a proud cactus standing alone in the desert.",
  "Sing a song while bouncing around like you're on a huge stage.",
  "Be a documentary narrator describing the humans sitting in this room.",
  "Invent a secret handshake and teach it to one person in the room.",
  "Imitate someone struggling to open a stuck soda bottle cap.",
  "Read out a wedding toast, but dedicated to two chopsticks.",
  "Depict a gloomy rainy day through a slow-motion dance.",
  "Sing a song and shout 'I'm still okay!' every time you run out of breath.",
  "Be a food critic tasting a glass of plain water and giving deep commentary.",
  "Introduce yourself with a goofy 4-line nursery-style poem.",
  "Imitate someone waiting forever for an elevator that never comes.",
  "Read out an advertisement you invent for a throw pillow.",
  "Act out being a robot vacuum stuck in the corner of the room.",
  "Sing a song while conducting an imaginary orchestra with your hands.",
  "Be an athlete receiving a gold medal and proudly singing the anthem.",
  "Critique your own hairstyle like a famous celebrity stylist.",
  "Imitate someone pretending to understand the lesson when called to the board.",
  "Read out the 'secret confessions' of your refrigerator.",
  "Express the feeling of eating something way too spicy using face and hands.",
  "Sing a whole song while hopping on one foot.",
  "Be a magazine model switching 5 poses in 15 seconds.",
  "Crown yourself with a royal title and give the room a funny royal order.",
  "Imitate a pigeon bobbing its head while searching for food.",
  "Read a news report about you losing the bet in a very serious voice.",
  "Act out being a piece of candy slowly melting in someone's mouth.",
  "Sing a familiar song but with all the lines in reverse order.",
  "Be a yoga instructor and lead the room through 3 deep breaths.",
  "Imitate someone trying to look wide awake right after dozing off.",
  "Advertise yourself out loud as if you were an incredible bargain combo deal.",
];

export const CHALLENGE_SUGGESTIONS: Record<Locale, readonly string[]> = {
  vi: VI_SUGGESTIONS,
  en: EN_SUGGESTIONS,
};

/**
 * Pick a random dare suggestion for the given locale. Pass the current input as
 * `exclude` to avoid handing back the exact same suggestion twice in a row.
 * Falls back to the English list for unknown locales.
 */
export function pickRandomChallenge(locale: Locale, exclude?: string): string {
  const list = CHALLENGE_SUGGESTIONS[locale] ?? CHALLENGE_SUGGESTIONS.en;
  if (list.length === 0) {
    return "";
  }
  if (list.length === 1) {
    return list[0];
  }

  let pick = list[Math.floor(Math.random() * list.length)];
  for (let guard = 0; pick === exclude && guard < 8; guard += 1) {
    pick = list[Math.floor(Math.random() * list.length)];
  }
  return pick;
}
