const REGIONAL_INDICATOR_OFFSET = 0x1f1e6 - "A".charCodeAt(0);

const isoToFlagEmoji = (isoCode: string): string =>
  String.fromCodePoint(
    ...[...isoCode.toUpperCase()].map(
      (char) => char.charCodeAt(0) + REGIONAL_INDICATOR_OFFSET,
    ),
  );

// Subdivision flags without an ISO 3166-1 alpha-2 code.
const flagOverrideByTeamName: Record<string, string> = {
  england: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  scotland: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  wales: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}",
};

// Team names as reported by The Odds API, normalized via normalizeTeamName.
const isoCodeByTeamName: Record<string, string> = {
  albania: "AL",
  algeria: "DZ",
  angola: "AO",
  argentina: "AR",
  armenia: "AM",
  australia: "AU",
  austria: "AT",
  azerbaijan: "AZ",
  bahrain: "BH",
  belarus: "BY",
  belgium: "BE",
  benin: "BJ",
  bolivia: "BO",
  "bosnia and herzegovina": "BA",
  botswana: "BW",
  brazil: "BR",
  bulgaria: "BG",
  "burkina faso": "BF",
  "cabo verde": "CV",
  cameroon: "CM",
  canada: "CA",
  "cape verde": "CV",
  chile: "CL",
  china: "CN",
  colombia: "CO",
  "costa rica": "CR",
  "cote d'ivoire": "CI",
  croatia: "HR",
  cuba: "CU",
  curacao: "CW",
  cyprus: "CY",
  "czech republic": "CZ",
  czechia: "CZ",
  denmark: "DK",
  "dominican republic": "DO",
  "dr congo": "CD",
  ecuador: "EC",
  egypt: "EG",
  "el salvador": "SV",
  "equatorial guinea": "GQ",
  estonia: "EE",
  ethiopia: "ET",
  finland: "FI",
  france: "FR",
  gabon: "GA",
  georgia: "GE",
  germany: "DE",
  ghana: "GH",
  greece: "GR",
  guatemala: "GT",
  guinea: "GN",
  "guinea-bissau": "GW",
  guyana: "GY",
  haiti: "HT",
  honduras: "HN",
  hungary: "HU",
  iceland: "IS",
  india: "IN",
  indonesia: "ID",
  "ir iran": "IR",
  iran: "IR",
  iraq: "IQ",
  ireland: "IE",
  israel: "IL",
  italy: "IT",
  "ivory coast": "CI",
  jamaica: "JM",
  japan: "JP",
  jordan: "JO",
  kazakhstan: "KZ",
  kenya: "KE",
  "korea dpr": "KP",
  "korea republic": "KR",
  kosovo: "XK",
  kuwait: "KW",
  latvia: "LV",
  lebanon: "LB",
  libya: "LY",
  lithuania: "LT",
  luxembourg: "LU",
  madagascar: "MG",
  malawi: "MW",
  malaysia: "MY",
  mali: "ML",
  malta: "MT",
  mauritania: "MR",
  mexico: "MX",
  moldova: "MD",
  montenegro: "ME",
  morocco: "MA",
  mozambique: "MZ",
  namibia: "NA",
  netherlands: "NL",
  "new zealand": "NZ",
  nicaragua: "NI",
  niger: "NE",
  nigeria: "NG",
  "north korea": "KP",
  "north macedonia": "MK",
  "northern ireland": "GB",
  norway: "NO",
  oman: "OM",
  palestine: "PS",
  panama: "PA",
  paraguay: "PY",
  peru: "PE",
  philippines: "PH",
  poland: "PL",
  portugal: "PT",
  qatar: "QA",
  "republic of ireland": "IE",
  romania: "RO",
  russia: "RU",
  rwanda: "RW",
  "saudi arabia": "SA",
  senegal: "SN",
  serbia: "RS",
  "sierra leone": "SL",
  singapore: "SG",
  slovakia: "SK",
  slovenia: "SI",
  "south africa": "ZA",
  "south korea": "KR",
  spain: "ES",
  sudan: "SD",
  suriname: "SR",
  sweden: "SE",
  switzerland: "CH",
  syria: "SY",
  tanzania: "TZ",
  thailand: "TH",
  togo: "TG",
  "trinidad and tobago": "TT",
  tunisia: "TN",
  turkey: "TR",
  turkiye: "TR",
  uae: "AE",
  uganda: "UG",
  ukraine: "UA",
  "united arab emirates": "AE",
  "united states": "US",
  uruguay: "UY",
  usa: "US",
  uzbekistan: "UZ",
  venezuela: "VE",
  vietnam: "VN",
  zambia: "ZM",
  zimbabwe: "ZW",
};

const normalizeTeamName = (teamName: string): string =>
  teamName
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s*&\s*/g, " and ")
    .toLowerCase()
    .trim();

export const getTeamFlag = (teamName: string): string => {
  const normalized = normalizeTeamName(teamName);

  const override = flagOverrideByTeamName[normalized];
  if (override) {
    return override;
  }

  const isoCode = isoCodeByTeamName[normalized];
  return isoCode ? isoToFlagEmoji(isoCode) : "\u{1F3F3}\u{FE0F}";
};
